--- #YAML:1.0
name:               XML-Filter-ExceptionLocator
version:            1.01
abstract:           filter to add line/col numbers to SAX errors
author:
    - Sam Tregar <sam@tregar.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:         0
    XML::SAX:           0
    XML::SAX::ExpatXS:  1.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
